server:
  port: 8765
  error:
    include-stacktrace: never

spring:
  config:
    import:
      - classpath:/keycloak.yml
      - classpath:/springdoc.yml
      - classpath:/management.yml
      - classpath:/logging.yml
      - classpath:/security.yml
  application:
    name: '@project.name@'
  devtools:
    restart:
      enabled: false
  security:
    user:
      name: admin
      password: admin
      roles: ${ROLES}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client.id}
          client-secret: ${keycloak.client.secret}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
            allowed-headers: '*'
            allowed-methods: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orquestador
          uri:  ${URL_ORQUESTADOR}
          predicates:
            - Path=/api/orquestador/**
        - id: feedback
          uri:  ${URL_FEEDBACK}
          predicates:
            - Path=/api/administrador-entrevista/**
        - id: notificaciones
          uri:  ${URL_WEBSOCKET}
          predicates:
            - Path=/api/notificaciones/**

logging:
  level:
    org.springframework.security.oauth2: DEBUG

