application:
  security:
    white-list:
      - /webjars/**
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /*/*/v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/ui
      - /configuration/security
      - /actuator/**
      - /*/actuator/**
      - /error
      - /sso/logout
      - /logout
      - /api/ms1/secret
      - /api/orquestador/v1/entrevistador/public/preguntas
      - /api/orquestador/v1/entrevistador/cv/**
      - /canalWS/**